dist: bionic
language: node_js
node_js:
  - "10.0"
  - "11.0"
  - "12.0"
before_install:
  - sudo apt-get update
  - sudo apt-get install clamav clamav-daemon
  - sudo systemctl stop clamav-freshclam
  - sudo freshclam -v
  - sudo systemctl restart clamav-daemon
